version: "3.8"

services:
  api:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.api
    ports:
      - "8000:8000"

  dashboard:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.dashboard
    ports:
      - "8501:8501"
